import { Shield, Download, Share2, FileText, Copy } from 'lucide-react';
import { useState } from 'react';
import { Card, Button, Badge } from '@/components/ui';
import type { CyraDoctorReport, RiskItem } from '@/lib/reports';
import { exportDoctorReportPdf, formatReportAsText } from '@/lib/reports';
import { cn } from '@/lib/tokens';

interface ReportExportPanelProps {
  report: CyraDoctorReport;
  risks: RiskItem[];
  onShare?: () => void;
}

const SEVERITY_STYLE = {
  low: 'bg-wellness-50 border-wellness-200 text-wellness-700',
  moderate: 'bg-risk-moderate-bg border-risk-moderate-border text-risk-moderate',
  high: 'bg-risk-high-bg border-risk-high-border text-risk-high',
};

export function ReportExportPanel({ report, risks, onShare }: ReportExportPanelProps) {
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState(false);

  const downloadPdf = () => {
    setExporting(true);
    try {
      exportDoctorReportPdf(report);
      onShare?.();
    } finally {
      setTimeout(() => setExporting(false), 600);
    }
  };

  const downloadText = () => {
    const blob = new Blob([formatReportAsText(report)], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cyra-report-${report.date_range_end}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyAll = async () => {
    await navigator.clipboard.writeText(formatReportAsText(report));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const shareNative = async () => {
    const text = formatReportAsText(report);
    if (navigator.share) {
      await navigator.share({ title: report.title, text });
      onShare?.();
    } else {
      await copyAll();
    }
  };

  return (
    <div className="space-y-4 animate-slide-up">
      <Card className="border-border bg-surface">
        <div>
          <div className="mb-1 flex items-center gap-2">
            <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-brand-500 text-white font-display font-bold">
              C
            </div>
            <div>
              <p className="font-display text-title text-ink">Premium export</p>
              <p className="text-micro text-ink-tertiary">Branded PDF for your clinician</p>
            </div>
          </div>
          <p className="mt-4 text-caption text-ink-secondary leading-relaxed">
            Your report includes patient info, health summary, cycle table, symptom timeline, trend charts,
            discussion checklist, risk summary, and medical disclaimer — all branded with Cyra.
          </p>
          <div className="mt-5 flex flex-wrap gap-2">
            <Button onClick={downloadPdf} loading={exporting}>
              <Download className="h-4 w-4" aria-hidden="true" />
              Download PDF
            </Button>
            <Button variant="secondary" onClick={shareNative}>
              <Share2 className="h-4 w-4" aria-hidden="true" />
              Share
            </Button>
            <Button variant="ghost" onClick={copyAll}>
              <Copy className="h-4 w-4" aria-hidden="true" />
              {copied ? 'Copied!' : 'Copy text'}
            </Button>
            <Button variant="ghost" onClick={downloadText}>
              <FileText className="h-4 w-4" aria-hidden="true" />
              .txt
            </Button>
          </div>
        </div>
      </Card>

      <Card>
        <div className="mb-3 flex items-center gap-2">
          <Shield className="h-5 w-5 text-brand-500" aria-hidden="true" />
          <p className="section-label !mb-0">Risk summary</p>
        </div>
        <p className="mb-4 text-micro text-ink-muted">
          Observational flags from your logs — not a diagnosis. Discuss with your healthcare provider.
        </p>
        <ul className="space-y-3">
          {risks.map((r) => (
            <li
              key={r.concern}
              className={cn('rounded-2xl border px-4 py-3', SEVERITY_STYLE[r.severity])}
            >
              <div className="flex items-center gap-2">
                <p className="text-caption font-medium">{r.concern}</p>
                <Badge variant="outline" className="!text-[10px] capitalize">{r.severity}</Badge>
              </div>
              <p className="mt-1 text-micro opacity-90">{r.note}</p>
            </li>
          ))}
        </ul>
      </Card>

      <Card className="bg-surface-secondary">
        <p className="section-label mb-2">Disclaimer</p>
        <p className="text-micro text-ink-muted leading-relaxed">
          This report is generated by Cyra from self-reported tracking data. It supports conversations with
          healthcare providers and does not diagnose, treat, or replace medical advice. If you experience severe
          symptoms, seek immediate medical care.
        </p>
      </Card>
    </div>
  );
}
